// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sphene.API.Dto.Files;
using SpheneShared.Data;

#nullable disable

namespace SpheneServer.Migrations
{
    [DbContext(typeof(SpheneDbContext))]
    [Migration("20260112111025_AddPendingFileTransfers")]
    partial class AddPendingFileTransfers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpheneShared.Models.AreaBoundLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("division_id");

                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<int>("HouseId")
                        .HasColumnType("integer")
                        .HasColumnName("house_id");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<int>("MatchingMode")
                        .HasColumnType("integer")
                        .HasColumnName("matching_mode");

                    b.Property<byte>("RoomId")
                        .HasColumnType("smallint")
                        .HasColumnName("room_id");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.Property<long>("TerritoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("territory_id");

                    b.Property<int>("WardId")
                        .HasColumnType("integer")
                        .HasColumnName("ward_id");

                    b.HasKey("Id")
                        .HasName("pk_area_bound_locations");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_area_bound_locations_group_gid");

                    b.HasIndex("ServerId", "MapId")
                        .HasDatabaseName("ix_area_bound_locations_server_id_map_id");

                    b.HasIndex("ServerId", "TerritoryId")
                        .HasDatabaseName("ix_area_bound_locations_server_id_territory_id");

                    b.ToTable("area_bound_locations", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.AreaBoundSyncshell", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<bool>("AutoBroadcastEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_broadcast_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomJoinMessage")
                        .HasColumnType("text")
                        .HasColumnName("custom_join_message");

                    b.Property<string>("JoinRules")
                        .HasColumnType("text")
                        .HasColumnName("join_rules");

                    b.Property<int>("MaxAutoJoinUsers")
                        .HasColumnType("integer")
                        .HasColumnName("max_auto_join_users");

                    b.Property<bool>("NotifyOnUserEnter")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_user_enter");

                    b.Property<bool>("NotifyOnUserLeave")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_user_leave");

                    b.Property<bool>("RequireOwnerPresence")
                        .HasColumnType("boolean")
                        .HasColumnName("require_owner_presence");

                    b.Property<bool>("RequireRulesAcceptance")
                        .HasColumnType("boolean")
                        .HasColumnName("require_rules_acceptance");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rules_version");

                    b.HasKey("GroupGID")
                        .HasName("pk_area_bound_syncshells");

                    b.HasIndex("AutoBroadcastEnabled")
                        .HasDatabaseName("ix_area_bound_syncshells_auto_broadcast_enabled");

                    b.ToTable("area_bound_syncshells", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.AreaBoundSyncshellConsent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AcceptedRulesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_rules_version");

                    b.Property<DateTime>("ConsentGivenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_given_at");

                    b.Property<bool>("HasAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("has_accepted");

                    b.Property<DateTime?>("LastRulesAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rules_accepted_at");

                    b.Property<string>("SyncshellGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("syncshell_gid");

                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.HasKey("Id")
                        .HasName("pk_area_bound_syncshell_consents");

                    b.HasIndex("SyncshellGID")
                        .HasDatabaseName("ix_area_bound_syncshell_consents_syncshell_gid");

                    b.HasIndex("UserUID", "SyncshellGID")
                        .IsUnique()
                        .HasDatabaseName("ix_area_bound_syncshell_consents_user_uid_syncshell_gid");

                    b.ToTable("area_bound_syncshell_consents", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.Auth", b =>
                {
                    b.Property<string>("HashedKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hashed_key");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<bool>("MarkForBan")
                        .HasColumnType("boolean")
                        .HasColumnName("mark_for_ban");

                    b.Property<string>("PrimaryUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("primary_user_uid");

                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.HasKey("HashedKey")
                        .HasName("pk_auth");

                    b.HasIndex("PrimaryUserUID")
                        .HasDatabaseName("ix_auth_primary_user_uid");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_auth_user_uid");

                    b.ToTable("auth", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.Banned", b =>
                {
                    b.Property<string>("CharacterIdentification")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("character_identification");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("CharacterIdentification")
                        .HasName("pk_banned_users");

                    b.ToTable("banned_users", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.BannedRegistrations", b =>
                {
                    b.Property<string>("DiscordIdOrLodestoneAuth")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discord_id_or_lodestone_auth");

                    b.HasKey("DiscordIdOrLodestoneAuth")
                        .HasName("pk_banned_registrations");

                    b.ToTable("banned_registrations", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.CharaData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("UploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uploader_uid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer")
                        .HasColumnName("access_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CustomizeData")
                        .HasColumnType("text")
                        .HasColumnName("customize_data");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("GlamourerData")
                        .HasColumnType("text")
                        .HasColumnName("glamourer_data");

                    b.Property<string>("HeelsData")
                        .HasColumnType("text")
                        .HasColumnName("heels_data");

                    b.Property<string>("HonorificData")
                        .HasColumnType("text")
                        .HasColumnName("honorific_data");

                    b.Property<string>("ManipulationData")
                        .HasColumnType("text")
                        .HasColumnName("manipulation_data");

                    b.Property<string>("MoodlesData")
                        .HasColumnType("text")
                        .HasColumnName("moodles_data");

                    b.Property<string>("PetNamesData")
                        .HasColumnType("text")
                        .HasColumnName("pet_names_data");

                    b.Property<int>("ShareType")
                        .HasColumnType("integer")
                        .HasColumnName("share_type");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id", "UploaderUID")
                        .HasName("pk_chara_data");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_chara_data_id");

                    b.HasIndex("UploaderUID")
                        .HasDatabaseName("ix_chara_data_uploader_uid");

                    b.ToTable("chara_data", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataAllowance", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedGroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("allowed_group_gid");

                    b.Property<string>("AllowedUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("allowed_user_uid");

                    b.HasKey("ParentId", "ParentUploaderUID", "Id")
                        .HasName("pk_chara_data_allowance");

                    b.HasIndex("AllowedGroupGID")
                        .HasDatabaseName("ix_chara_data_allowance_allowed_group_gid");

                    b.HasIndex("AllowedUserUID")
                        .HasDatabaseName("ix_chara_data_allowance_allowed_user_uid");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_allowance_parent_id");

                    b.ToTable("chara_data_allowance", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataFile", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<string>("GamePath")
                        .HasColumnType("text")
                        .HasColumnName("game_path");

                    b.Property<string>("FileCacheHash")
                        .HasColumnType("character varying(40)")
                        .HasColumnName("file_cache_hash");

                    b.HasKey("ParentId", "ParentUploaderUID", "GamePath")
                        .HasName("pk_chara_data_files");

                    b.HasIndex("FileCacheHash")
                        .HasDatabaseName("ix_chara_data_files_file_cache_hash");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_files_parent_id");

                    b.ToTable("chara_data_files", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataFileSwap", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<string>("GamePath")
                        .HasColumnType("text")
                        .HasColumnName("game_path");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.HasKey("ParentId", "ParentUploaderUID", "GamePath")
                        .HasName("pk_chara_data_file_swaps");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_file_swaps_parent_id");

                    b.ToTable("chara_data_file_swaps", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataHash", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.HasKey("Id")
                        .HasName("pk_chara_data_hashes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_hashes_parent_id");

                    b.HasIndex("ParentId", "ParentUploaderUID")
                        .HasDatabaseName("ix_chara_data_hashes_parent_id_parent_uploader_uid");

                    b.ToTable("chara_data_hashes", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataOriginalFile", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<string>("GamePath")
                        .HasColumnType("text")
                        .HasColumnName("game_path");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.HasKey("ParentId", "ParentUploaderUID", "GamePath")
                        .HasName("pk_chara_data_orig_files");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_orig_files_parent_id");

                    b.ToTable("chara_data_orig_files", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataPose", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PoseData")
                        .HasColumnType("text")
                        .HasColumnName("pose_data");

                    b.Property<string>("WorldData")
                        .HasColumnType("text")
                        .HasColumnName("world_data");

                    b.HasKey("ParentId", "ParentUploaderUID", "Id")
                        .HasName("pk_chara_data_poses");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_poses_parent_id");

                    b.ToTable("chara_data_poses", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.ClientPair", b =>
                {
                    b.Property<string>("UserUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<string>("OtherUserUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("other_user_uid");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("UserUID", "OtherUserUID")
                        .HasName("pk_client_pairs");

                    b.HasIndex("OtherUserUID")
                        .HasDatabaseName("ix_client_pairs_other_user_uid");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_client_pairs_user_uid");

                    b.ToTable("client_pairs", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.FileCache", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hash");

                    b.Property<long>("RawSize")
                        .HasColumnType("bigint")
                        .HasColumnName("raw_size");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<bool>("Uploaded")
                        .HasColumnType("boolean")
                        .HasColumnName("uploaded");

                    b.Property<string>("UploaderUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uploader_uid");

                    b.HasKey("Hash")
                        .HasName("pk_file_caches");

                    b.HasIndex("UploaderUID")
                        .HasDatabaseName("ix_file_caches_uploader_uid");

                    b.ToTable("file_caches", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.ForbiddenUploadEntry", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hash");

                    b.Property<string>("ForbiddenBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("forbidden_by");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("Hash")
                        .HasName("pk_forbidden_upload_entries");

                    b.ToTable("forbidden_upload_entries", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.Group", b =>
                {
                    b.Property<string>("GID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gid");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("InvitesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("invites_enabled");

                    b.Property<string>("OwnerUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_uid");

                    b.Property<bool>("PreferDisableAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_disable_animations");

                    b.Property<bool>("PreferDisableSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_disable_sounds");

                    b.Property<bool>("PreferDisableVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_disable_vfx");

                    b.HasKey("GID")
                        .HasName("pk_groups");

                    b.HasIndex("OwnerUID")
                        .HasDatabaseName("ix_groups_owner_uid");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.GroupBan", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<string>("BannedUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("banned_user_uid");

                    b.Property<string>("BannedByUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("banned_by_uid");

                    b.Property<DateTime>("BannedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_on");

                    b.Property<string>("BannedReason")
                        .HasColumnType("text")
                        .HasColumnName("banned_reason");

                    b.HasKey("GroupGID", "BannedUserUID")
                        .HasName("pk_group_bans");

                    b.HasIndex("BannedByUID")
                        .HasDatabaseName("ix_group_bans_banned_by_uid");

                    b.HasIndex("BannedUserUID")
                        .HasDatabaseName("ix_group_bans_banned_user_uid");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_group_bans_group_gid");

                    b.ToTable("group_bans", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.GroupPair", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<string>("GroupUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("group_user_uid");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_moderator");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.HasKey("GroupGID", "GroupUserUID")
                        .HasName("pk_group_pairs");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_group_pairs_group_gid");

                    b.HasIndex("GroupUserUID")
                        .HasDatabaseName("ix_group_pairs_group_user_uid");

                    b.ToTable("group_pairs", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.GroupPairPreferredPermission", b =>
                {
                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<bool>("DisableAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_animations");

                    b.Property<bool>("DisableSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_sounds");

                    b.Property<bool>("DisableVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_vfx");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.HasKey("UserUID", "GroupGID")
                        .HasName("pk_group_pair_preferred_permissions");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_group_pair_preferred_permissions_group_gid");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_group_pair_preferred_permissions_user_uid");

                    b.ToTable("group_pair_preferred_permissions", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.GroupTempInvite", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<string>("Invite")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.HasKey("GroupGID", "Invite")
                        .HasName("pk_group_temp_invites");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_group_temp_invites_group_gid");

                    b.HasIndex("Invite")
                        .HasDatabaseName("ix_group_temp_invites_invite");

                    b.ToTable("group_temp_invites", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.LodeStoneAuth", b =>
                {
                    b.Property<decimal>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<string>("HashedLodestoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hashed_lodestone_id");

                    b.Property<string>("LodestoneAuthString")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lodestone_auth_string");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.HasKey("DiscordId")
                        .HasName("pk_lodestone_auth");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_lodestone_auth_user_uid");

                    b.ToTable("lodestone_auth", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.ModDownloadHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloaded_at");

                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hash");

                    b.Property<string>("UserUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.HasKey("Id")
                        .HasName("pk_mod_download_history");

                    b.HasIndex("DownloadedAt")
                        .HasDatabaseName("ix_mod_download_history_downloaded_at");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_mod_download_history_hash");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_mod_download_history_user_uid");

                    b.ToTable("mod_download_history", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.ModFile", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_date");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Hash")
                        .HasName("pk_mod_files");

                    b.ToTable("mod_files", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.PendingFileTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("ModFolderName")
                        .HasColumnType("text")
                        .HasColumnName("mod_folder_name");

                    b.Property<List<ModInfoDto>>("ModInfo")
                        .HasColumnType("jsonb")
                        .HasColumnName("mod_info");

                    b.Property<string>("RecipientUID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_uid");

                    b.Property<string>("SenderAlias")
                        .HasColumnType("text")
                        .HasColumnName("sender_alias");

                    b.Property<string>("SenderUID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sender_uid");

                    b.HasKey("Id")
                        .HasName("pk_pending_file_transfers");

                    b.HasIndex("RecipientUID")
                        .HasDatabaseName("ix_pending_file_transfers_recipient_uid");

                    b.ToTable("pending_file_transfers", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.SyncshellWelcomePage", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("image_content_type");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_file_name");

                    b.Property<long?>("ImageSize")
                        .HasColumnType("bigint")
                        .HasColumnName("image_size");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("ShowOnAreaBoundJoin")
                        .HasColumnType("boolean")
                        .HasColumnName("show_on_area_bound_join");

                    b.Property<bool>("ShowOnJoin")
                        .HasColumnType("boolean")
                        .HasColumnName("show_on_join");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WelcomeImageBase64")
                        .HasColumnType("text")
                        .HasColumnName("welcome_image_base64");

                    b.Property<string>("WelcomeText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("welcome_text");

                    b.HasKey("GroupGID")
                        .HasName("pk_syncshell_welcome_pages");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_syncshell_welcome_pages_is_enabled");

                    b.ToTable("syncshell_welcome_pages", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.User", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uid");

                    b.Property<string>("Alias")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("alias");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_moderator");

                    b.Property<DateTime>("LastLoggedIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_logged_in");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("UID")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.UserDefaultPreferredPermission", b =>
                {
                    b.Property<string>("UserUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<bool>("DisableGroupAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_group_animations");

                    b.Property<bool>("DisableGroupSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_group_sounds");

                    b.Property<bool>("DisableGroupVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_group_vfx");

                    b.Property<bool>("DisableIndividualAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_individual_animations");

                    b.Property<bool>("DisableIndividualSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_individual_sounds");

                    b.Property<bool>("DisableIndividualVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_individual_vfx");

                    b.Property<bool>("IndividualIsSticky")
                        .HasColumnType("boolean")
                        .HasColumnName("individual_is_sticky");

                    b.HasKey("UserUID")
                        .HasName("pk_user_default_preferred_permissions");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_user_default_preferred_permissions_user_uid");

                    b.ToTable("user_default_preferred_permissions", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.UserHousingProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowIndoor")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_indoor");

                    b.Property<bool>("AllowOutdoor")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_outdoor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("division_id");

                    b.Property<long>("HouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("house_id");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_indoor");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<bool>("PreferIndoorSyncshells")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_indoor_syncshells");

                    b.Property<bool>("PreferOutdoorSyncshells")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_outdoor_syncshells");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<long>("TerritoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("territory_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.HasKey("Id")
                        .HasName("pk_user_housing_properties");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_user_housing_properties_user_uid");

                    b.HasIndex("UserUID", "ServerId", "TerritoryId", "WardId", "HouseId", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_housing_properties_user_uid_server_id_territory_id_war");

                    b.ToTable("user_housing_properties", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.UserPermissionSet", b =>
                {
                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<string>("OtherUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("other_user_uid");

                    b.Property<bool>("AckYou")
                        .HasColumnType("boolean")
                        .HasColumnName("ack_you");

                    b.Property<bool>("DisableAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_animations");

                    b.Property<bool>("DisableSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_sounds");

                    b.Property<bool>("DisableVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_vfx");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<bool>("Sticky")
                        .HasColumnType("boolean")
                        .HasColumnName("sticky");

                    b.HasKey("UserUID", "OtherUserUID")
                        .HasName("pk_user_permission_sets");

                    b.HasIndex("OtherUserUID")
                        .HasDatabaseName("ix_user_permission_sets_other_user_uid");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_user_permission_sets_user_uid");

                    b.HasIndex("UserUID", "OtherUserUID", "IsPaused")
                        .HasDatabaseName("ix_user_permission_sets_user_uid_other_user_uid_is_paused");

                    b.ToTable("user_permission_sets", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.UserProfileData", b =>
                {
                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<string>("Base64ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("base64profile_image");

                    b.Property<bool>("FlaggedForReport")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged_for_report");

                    b.Property<bool>("IsNSFW")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<bool>("ProfileDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("profile_disabled");

                    b.Property<string>("UserDescription")
                        .HasColumnType("text")
                        .HasColumnName("user_description");

                    b.HasKey("UserUID")
                        .HasName("pk_user_profile_data");

                    b.ToTable("user_profile_data", (string)null);
                });

            modelBuilder.Entity("SpheneShared.Models.AreaBoundLocation", b =>
                {
                    b.HasOne("SpheneShared.Models.AreaBoundSyncshell", "AreaBoundSyncshell")
                        .WithMany("Locations")
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_area_bound_locations_area_bound_syncshells_group_gid");

                    b.Navigation("AreaBoundSyncshell");
                });

            modelBuilder.Entity("SpheneShared.Models.AreaBoundSyncshell", b =>
                {
                    b.HasOne("SpheneShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_area_bound_syncshells_groups_group_gid");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SpheneShared.Models.AreaBoundSyncshellConsent", b =>
                {
                    b.HasOne("SpheneShared.Models.Group", "Syncshell")
                        .WithMany()
                        .HasForeignKey("SyncshellGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_area_bound_syncshell_consents_groups_syncshell_gid");

                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_area_bound_syncshell_consents_users_user_uid");

                    b.Navigation("Syncshell");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.Auth", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "PrimaryUser")
                        .WithMany()
                        .HasForeignKey("PrimaryUserUID")
                        .HasConstraintName("fk_auth_users_primary_user_uid");

                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .HasConstraintName("fk_auth_users_user_uid");

                    b.Navigation("PrimaryUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaData", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_users_uploader_uid");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataAllowance", b =>
                {
                    b.HasOne("SpheneShared.Models.Group", "AllowedGroup")
                        .WithMany()
                        .HasForeignKey("AllowedGroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_chara_data_allowance_groups_allowed_group_gid");

                    b.HasOne("SpheneShared.Models.User", "AllowedUser")
                        .WithMany()
                        .HasForeignKey("AllowedUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_chara_data_allowance_users_allowed_user_uid");

                    b.HasOne("SpheneShared.Models.CharaData", "Parent")
                        .WithMany("AllowedIndividiuals")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_allowance_chara_data_parent_id_parent_uploader_u");

                    b.Navigation("AllowedGroup");

                    b.Navigation("AllowedUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataFile", b =>
                {
                    b.HasOne("SpheneShared.Models.FileCache", "FileCache")
                        .WithMany()
                        .HasForeignKey("FileCacheHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_chara_data_files_files_file_cache_hash");

                    b.HasOne("SpheneShared.Models.CharaData", "Parent")
                        .WithMany("Files")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_files_chara_data_parent_id_parent_uploader_uid");

                    b.Navigation("FileCache");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataFileSwap", b =>
                {
                    b.HasOne("SpheneShared.Models.CharaData", "Parent")
                        .WithMany("FileSwaps")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_file_swaps_chara_data_parent_id_parent_uploader_");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataHash", b =>
                {
                    b.HasOne("SpheneShared.Models.CharaData", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .HasConstraintName("fk_chara_data_hashes_chara_data_parent_id_parent_uploader_uid");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataOriginalFile", b =>
                {
                    b.HasOne("SpheneShared.Models.CharaData", "Parent")
                        .WithMany("OriginalFiles")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_orig_files_chara_data_parent_id_parent_uploader_");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaDataPose", b =>
                {
                    b.HasOne("SpheneShared.Models.CharaData", "Parent")
                        .WithMany("Poses")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_poses_chara_data_parent_id_parent_uploader_uid");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SpheneShared.Models.ClientPair", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "OtherUser")
                        .WithMany()
                        .HasForeignKey("OtherUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pairs_users_other_user_uid");

                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pairs_users_user_uid");

                    b.Navigation("OtherUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.FileCache", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderUID")
                        .HasConstraintName("fk_file_caches_users_uploader_uid");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("SpheneShared.Models.Group", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUID")
                        .HasConstraintName("fk_groups_users_owner_uid");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SpheneShared.Models.GroupBan", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedByUID")
                        .HasConstraintName("fk_group_bans_users_banned_by_uid");

                    b.HasOne("SpheneShared.Models.User", "BannedUser")
                        .WithMany()
                        .HasForeignKey("BannedUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_bans_users_banned_user_uid");

                    b.HasOne("SpheneShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_bans_groups_group_gid");

                    b.Navigation("BannedBy");

                    b.Navigation("BannedUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SpheneShared.Models.GroupPair", b =>
                {
                    b.HasOne("SpheneShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_pairs_groups_group_gid");

                    b.HasOne("SpheneShared.Models.User", "GroupUser")
                        .WithMany()
                        .HasForeignKey("GroupUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_pairs_users_group_user_uid");

                    b.Navigation("Group");

                    b.Navigation("GroupUser");
                });

            modelBuilder.Entity("SpheneShared.Models.GroupPairPreferredPermission", b =>
                {
                    b.HasOne("SpheneShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_pair_preferred_permissions_groups_group_gid");

                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_pair_preferred_permissions_users_user_uid");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.GroupTempInvite", b =>
                {
                    b.HasOne("SpheneShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_temp_invites_groups_group_gid");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SpheneShared.Models.LodeStoneAuth", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .HasConstraintName("fk_lodestone_auth_users_user_uid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.SyncshellWelcomePage", b =>
                {
                    b.HasOne("SpheneShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_syncshell_welcome_pages_groups_group_gid");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SpheneShared.Models.UserDefaultPreferredPermission", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_default_preferred_permissions_users_user_uid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.UserHousingProperty", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_housing_properties_users_user_uid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.UserPermissionSet", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "OtherUser")
                        .WithMany()
                        .HasForeignKey("OtherUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_sets_users_other_user_uid");

                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_sets_users_user_uid");

                    b.Navigation("OtherUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.UserProfileData", b =>
                {
                    b.HasOne("SpheneShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_data_users_user_uid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpheneShared.Models.AreaBoundSyncshell", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("SpheneShared.Models.CharaData", b =>
                {
                    b.Navigation("AllowedIndividiuals");

                    b.Navigation("FileSwaps");

                    b.Navigation("Files");

                    b.Navigation("OriginalFiles");

                    b.Navigation("Poses");
                });
#pragma warning restore 612, 618
        }
    }
}
